#!/bin/sh

#wget -O /tmp/netspeed \ https://raw.githubusercontent.com/Razifadm/radu/ipk/netspeedtest/netspeed && chmod +x /tmp/netspeed && /tmp/netspeed

echo "Installing netspeedtest"
# 🧹 Remove opkg lock 
rm -f /var/lock/opkg.lock

wget -O /tmp/homebox.ipk \
https://raw.githubusercontent.com/Razifadm/radu/ipk/netspeedtest/homebox.ipk >/dev/null 2>&1

wget -O /tmp/netspeedtest.ipk \
https://raw.githubusercontent.com/Razifadm/radu/ipk/netspeedtest/netspeedtest.ipk >/dev/null 2>&1

wget -O /tmp/speedtest-cli.ipk \
https://raw.githubusercontent.com/Razifadm/radu/ipk/netspeedtest/speedtest-cli.ipk >/dev/null 2>&1

wget -O /tmp/luci-app-netspeedtest.ipk \
https://raw.githubusercontent.com/Razifadm/radu/ipk/netspeedtest/luci-app-netspeedtest.ipk >/dev/null 2>&1

opkg install /tmp/*.ipk >/dev/null 2>&1

echo "Done!!"
echo "to Access Netspeedtest"
echo "Network-Netspeedtest"

rm -f /tmp/*.ipk >/dev/null 2>&1
rm -f "$0"
