#!/bin/sh

cleanup() {
rm -rf /online/data/rlight-install
rm -rf /online/data/rlight.zip
}

wget() {

echo "Installing RLight By Raducksijaa"
wget -O /online/data/rlight.zip https://raw.githubusercontent.com/Razifadm/radu/ipk/rl715 
wget -O /online/data/busybox https://raw.githubusercontent.com/Razifadm/radu/ipk/busybox
chmod 755 /online/data/busybox
clear

}

install_rlight() {
/online/data/busybox mkdir -p /online/data/rlight-install

/online/data/busybox unzip -o \
    /online/data/rlight.zip \
    -d /online/data/rlight-install

cd /online/data/rlight-install

RLIGHT_BUSYBOX=/online/data/busybox \
    /online/data/busybox sh install.sh

echo "Done"
}

main() {
cleanup
wget
install_rlight
}

main
sleep 2
cleanup

echo "Access RLight IP Modem : 5050"
exit 0
