#!/bin/sh /etc/rc.common
# SSHWS Daemon Service (uses wrapper)
START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/sshws-wrapper
    # kita guna loop di wrapper jadi tak perlu procd respawn
    procd_close_instance
}

stop_service() {
    # stop by killing wrapper or any sshws instance
    killall sshws-wrapper >/dev/null 2>&1 || true
    killall sshws >/dev/null 2>&1 || true
}
