#!/bin/sh
LOG=/var/log/sshws.log
CONFIG=/root/config.json
mkdir -p /var/log

while true; do
    echo "$(date '+%F %T') - starting sshws" >> "$LOG"
    /usr/bin/sshws -c "$CONFIG" >> "$LOG" 2>&1
    echo "$(date '+%F %T') - sshws exited with code $?, restarting in 5s..." >> "$LOG"
    sleep 5
done
