#!/bin/sh

#wget -O /tmp/pwb https://raw.githubusercontent.com/Razifadm/radu/ipk/passwall/pwbanner && chmod +x /tmp/pwb && /tmp/pwb

opkg list-installed | grep -q "luci-app-passwall - 4\.67" || { echo "❌ luci-app-passwall not version 4.67 — STOPPED!"; exit 1; }

echo "This Process will install Banner IP on Passwall webui"
echo""
echo "Downloading Passwall Banner"

#rm -f /usr/lib/lua/luci/controller/passwall.lua >/dev/null 2>&1
wget -O /usr/lib/lua/luci/controller/passwall.lua https://raw.githubusercontent.com/Razifadm/radu/ipk/passwall/passwall.lua >/dev/null 2>&1
sleep 1

#rm -f /usr/lib/lua/luci/model/cbi/passwall/client/global.lua >/dev/null 2>&1
wget -O /usr/lib/lua/luci/model/cbi/passwall/client/global.lua https://raw.githubusercontent.com/Razifadm/radu/ipk/passwall/global.lua >/dev/null 2>&1
sleep 1

#rm -f /usr/lib/lua/luci/view/passwall/global/status_bottom.htm >/dev/null 2>&1
wget -O /usr/lib/lua/luci/view/passwall/global/status_bottom.htm https://raw.githubusercontent.com/Razifadm/radu/ipk/passwall/status.htm >/dev/null 2>&1

wget -O /tmp/passwall1.zip https://raw.githubusercontent.com/Razifadm/radu/ipk/passwall/passwall1.zip >/dev/null 2>&1 && unzip -o /tmp/passwall1.zip -d /www/luci-static >/dev/null 2>&1

echo "Banner Ip Passwall installed"
echo ""
/etc/init.d/uhttpd restart >/dev/null 2>&1
rm -f "$0" >/dev/null 2>&1
