#!/bin/sh

#wget -O /tmp/xlitecore https://raw.githubusercontent.com/Razifadm/radu/ipk/xlite/xlitecore && chmod +x /tmp/xlitecore && /tmp/xlitecore
XRAY_BINARY="xlite"
SCRIPT_PATH="/tmp/install.sh"
TMP_XRAY="/tmp/xrayxlitevpnje"

echo "Passwall 2 Xlite Core"
echo "updating xray core to latest version"
wget -O "$TMP_XRAY" https://raw.githubusercontent.com/Razifadm/radu/ipk/"$XRAY_BINARY"  >/dev/null 2>&1 

if [ ! -s "$TMP_XRAY" ]; then
    echo "❌ Download failed or empty file!"
    echo "⚠️ Update aborted."
    rm -f "$TMP_XRAY"
    exit 1
fi

#stop passwall services
/etc/init.d/passwall stop >/dev/null 2>&1 
/etc/init.d/passwall2 stop >/dev/null 2>&1 
sleep 1 >/dev/null 2>&1 

#remove current xray and replace with new one
rm -rf /usr/bin/xray
mv $TMP_XRAY /usr/bin/xlite >/dev/null 2>&1 

#chmod permission new xray, strxcore
chmod +x /usr/bin/xlite >/dev/null 2>&1 

#setting xray path to xlite core
#uci set passwall.@global_app[0].xray_file='/usr/bin/xlite'
uci set passwall2.@global_app[0].xray_file='/usr/bin/xlite'
#uci commit passwall
uci commit passwall2

echo "core updated to $XRAY_BINARY"
echo "xray path set to /usr/bin/xlite"
echo "if you are using passwall1/2 please restart it!!"
xray --version
rm -f "$0"
