#!/bin/sh

echo "📦this will install luci-theme-Peditx"

#download luci-app-peditx
#install peditx
#sleep sekejap
#download config etc/config/peditx
#echo done installation

#link format download
# wget -O /tmp/peditx \https://raw.githubusercontent.com/Razifadm/radu/ipk/themes/Peditx/Peditx && chmod +x /tmp/peditx && /tmp/peditx

#Download ipk
wget -O /tmp/luci-theme-peditx_1.2.3-01_all.ipk \https://github.com/peditx/luci-theme-peditx/releases/download/v1.2.3/luci-theme-peditx_1.2.3-01_all.ipk >/dev/null 2>&1

#opkg install theme peditx
echo "Installing themes-Peditx"
opkg install /tmp/luci-theme-peditx_1.2.3-01_all.ipk
sleep 1

#remove ipk
rm -f /tmp/luci-theme-peditx_1.2.3-01_all.ipk

#Download config
wget -O /etc/config/peditx \ https://raw.githubusercontent.com/Razifadm/radu/ipk/config/peditx >/dev/null 2>&1

rm -f "$0" >/dev/null 2>&1
