#!/bin/sh

echo "📦 this will install luci-theme-Peditx"

# Download ipk
wget -O /tmp/luci-theme-peditx_1.2.3-01_all.ipk \
https://raw.githubusercontent.com/Razifadm/radu/ipk/luci-theme-peditx_1.2.3-01_all.ipk >/dev/null 2>&1

# Pasang theme
echo "Installing themes-Peditx"
opkg install /tmp/luci-theme-peditx_1.2.3-01_all.ipk
sleep 1

# Buang fail sementara
rm -f /tmp/luci-theme-peditx_1.2.3-01_all.ipk

# Download config peditx
wget -O /etc/config/peditx \
https://raw.githubusercontent.com/Razifadm/radu/ipk/config/peditx >/dev/null 2>&1

# Restart web UI
/etc/init.d/uhttpd restart

# Hapus skrip selepas jalan
rm -f "$0" >/dev/null 2>&1
